### ISSUE TITLE
error rankmirrors

### ISSUE THREAD

**Issue by Biedubbeljoe** [deadhead420/fetchmirrors#14]
Hi,

I installed your package, but I get the below error:

Enter the number(s) or code(s) corresponding to your country [4 9 US]: 34

You have selected the countries: Netherlands - is this correct [Y/n]: 

Fetching new mirrorlist from: https://www.archlinux.org/mirrorlist/?country=NL
Please wait while ranking Netherlands mirrors...
/usr/bin/fetchmirrors: line 218: rankmirrors: command not found
[fetchmirrors] Error: an error occured in ranking mirrorlist exiting...

Any idea how to fix this?

**Comment by Marten4n6** [comment]
You should install the [pacman-contrib](https://www.archlinux.org/packages/?name=pacman-contrib) package:
```sudo pacman -S pacman-contrib```

https://wiki.archlinux.org/index.php/mirrors#List_by_speed

**Comment by Biedubbeljoe** [comment]
Thx mate, it's working!
