### ISSUE TITLE
AUR package does not install

### ISSUE THREAD

**Issue by haheute** [deadhead420/fetchmirrors#15]
The Archlinux AUR package does not install, here. It says md5sums failed for fetchmirrors.sh and: 

`:: failed to verify integrity or prepare fetchmirrors package`

Maybe the checksum does not fit..(?) 

thank you

**Comment by germelcar** [comment]
I think the problem has been fixed. I have updated fetchmirrors today and everything is OK.

**Comment by haheute** [comment]
I can't confirm, because not on archlinux currently.
Thanks
