### ISSUE TITLE
multiple select not working

### ISSUE THREAD

**Issue by FadeMind** [deadhead420/fetchmirrors#2]
Multiple country select not working at all (but values in `[ ]` suggesting multi choice:
![screenshot_20160319_110349](https://cloud.githubusercontent.com/assets/9846948/13897919/462a83f6-edc2-11e5-8a6d-a6f8afd357cd.png)

**Comment by deadhead420** [comment]
That is not currently a feature however it is something I could add in. It wouldn't be too hard, will require a while loop. Will work on it a bit later when I have some time.

**Comment by deadhead420** [comment]
and yes I see how the values in [ ] can be misleading but it was intended as just an example. Will close this issue once I add the feature.

**Comment by deadhead420** [comment]
A year later I've finally added this... You can now select multiple countries by putting a space between them. For example you could do: 5 8 10
Also codes work too: US AU 28
